### ISSUE TITLE
Comments throws off diagnostic (cvc-complex-type.2.3) mark onto the wrong location in server.xml

### ISSUE THREAD

**Issue by dshimo** [OpenLiberty/liberty-language-server#163] opened 2023-02-28 18:12 UTC
The expected behavior is for the diagnostics/markers to appear on the text. This behavior is also observed in `pom.xml`
![image](https://user-images.githubusercontent.com/8934136/221941192-900d0b0a-e4a0-4050-808d-c0221ca2b9d8.png)

When a comment is in between the text and the `server` element, the diagnostic marks the comment on line 4 rather than line 12.
![image](https://user-images.githubusercontent.com/8934136/221940806-b394ec34-1e97-4da4-b294-18f2d2d4036e.png)
This issue does not seem to occur on `pom.xml`

Steps to recreate:
1. Create a `server.xml` with a `server` element
2. Put a comment with content into it
3. Type any text anywhere in the `server` element

This bug appears in IntelliJ and VSCode 
![image](https://user-images.githubusercontent.com/8934136/221942440-69203e12-0271-4b92-8964-d6e6991babf7.png)

**Comment by evie-lau** [comment] 2023-02-28 20:20
Reproduced the same issue in a `pom.xml` file in VS Code.
![image](https://user-images.githubusercontent.com/689163/221969141-232c7da2-96d8-4de2-9b14-93a3ed9a1172.png)

**Comment by cherylking** [comment] 2023-02-28 20:20
This may be an error in `LemMinX` itself since LCLS only does diagnostics for certain elements (featureManager/feature and include). All other elements are validate against the schema with `LemMinX` afaik.

**Comment by cherylking** [comment] 2023-02-28 20:21
> Reproduced the same issue in a pom.xml file in VS Code.

So that means it is not a LCLS issue, correct?

**Comment by kathrynkodama** [comment] 2023-02-28 20:27
I've opened https://github.com/eclipse/lemminx/issues/1495

**Comment by angelozerr** [comment] 2023-02-28 20:47
We will invedtigate the problem on lemminx, but when you say that you have the problem with IJ, it means that you have integrated lemminx in IJ?

If the answer is yes, could you give me a link to the repository which does that. Thanks!

**Comment by kathrynkodama** [comment] 2023-02-28 21:01
@angelozerr yes, in Liberty Tools for IntelliJ we are running LemMinX with the Liberty LS ext: https://github.com/OpenLiberty/liberty-tools-intellij

**Comment by angelozerr** [comment] 2023-02-28 21:09
Wow thats great! Thanks @kathrynkodama for your answer.

**Comment by kathrynkodama** [comment] 2023-03-02 16:12
With https://github.com/eclipse/lemminx/issues/1495 fixed, lemminx-liberty, LT for IntelliJ and LT for Eclipse will have to update to the latest LemMinX version containing the fix.

**Comment by cherylking** [comment] 2023-03-02 16:38
@kathrynkodama Any outlook on when that next version of Eclipse LemMinX is expected?

**Comment by angelozerr** [comment] 2023-03-02 16:52
For the moment it is not planned, but we would like to create 1.0.0 https://github.com/eclipse/lemminx/issues/1470 which will break API participant. Please follow this issue.

**Comment by cherylking** [comment] 2023-04-18 16:30
Release `0.25.0` was released today - https://github.com/eclipse/lemminx/blob/main/CHANGELOG.md

**Comment by cherylking** [comment] 2023-04-21 17:28
This is fixed in the 2.0-snapshot branch which will be merged into the main branch once the 1.0 release is published. Closing this issue.

**Closed by cherylking** 2023-04-21 17:28 UTC
